### ISSUE TITLE
ROSBridge is throwing a lot of errors due to get_image service of ed

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/robot-api#48]
Due to this non-existing service

**Comment by reinzor** [comment]
https://github.com/tue-robotics/robot-api/blob/master/lib/ed-robocup.js#L43

**Comment by reinzor** [comment]
Maybe is good to leave all the robocup stuff out :/

**Comment by reinzor** [comment]
Required for demo

**Comment by MatthijsBurgh** [comment]
This only happens when you open the challenge_open UI, without the ed_robocup plugin being loaded. So not really an issue.
